### ISSUE TITLE
HTML tags not escaped correctly

### ISSUE THREAD

**Issue by karls** [alexmingoia/pux-devtool#11]
Hi Alex,

I'm playing around with Pux and Pux Devtool. I noticed that when storing HTML in my app state, Pux Devtool displays it a bit funkily. E.g, like this 

![screen shot 2017-02-28 at 10 58 25](https://cloud.githubusercontent.com/assets/251402/23402764/ee29e0fe-fda4-11e6-8bfc-73180d71ac06.png)

Changing the `stateToString` slightly yields better results.

![screen shot on 2017-02-28 at 11 3a00 3a18](https://cloud.githubusercontent.com/assets/251402/23402823/2c284d5a-fda5-11e6-9e5a-2fd70136c8f0.png)

Essentially, `stateToString` would look something like this (only the `replace` section is changed):

```js
exports.stateToString = function (s) {
  return JSON.stringify(s, function (key, val) {
    if (!val.constructor.name.match(/(Object|Boolean|Array|String|Number|Date|Symbol)/)) {
      return exports.actionToString(val);
    }
    return val;
  }, 2)
  .replace(/&/g, "&amp;")
  .replace(/</g, "&lt;")
  .replace(/>/g, "&gt;")
  .replace(/"([^"]+)":/g, '$1:')
  .replace(/\n/g, '<br />')
  .replace(/  /g, '&nbsp;&nbsp;');
};
```

Would you be willing to update or accept a pull request?

**Comment by alexmingoia** [comment]
The new DevTool for Pux 8 is packaged as a chrome and firefox extension and does not have this issue.
